# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZMNetworkHelper' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZMNetworkHelper

pod 'AFNetworking'
pod 'ReactiveObjC'
pod 'SDCycleScrollView'
pod 'Masonry'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'MBProgressHUD'

end
